name: Deploy schema to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'schema/**'  # Only run when any file in schema/ changes

permissions:
  contents: write  # This is required to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./schema
          publish_branch: gh-pages
          destination_dir: .
