name: Deploy Schema to Cloudflare Pages
on:
  push:
    branches: [main]
    paths:
      - 'schema/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Deploy to Cloudflare Pages
        run: |
          wrangler pages deploy ./schema \
            --project-name=video-notation-schema \
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
