name: Deploy Schemas to Cloudflare Pages

on:
  push:
    paths:
      - 'schema/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: |
          wrangler pages deploy ./schema \
            --project-name=my-schema-project \
            --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
